apiVersion: v1 
kind: Service 
metadata: 
    name: loadbalancer
    namespace: sli 
spec: 
    type: LoadBalancer 
    ports: 
        - name: p2p 
          port: 80
    selector: 
        # name: my-deployment
        app: myapp